fail_fast: true
repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        entry: poetry run ruff check
        args: [--fix]
        language: system
        types: [file, python]
      - id: ruff-format
        name: Ruff format
        entry: poetry run ruff format
        language: system
        types: [file, python]
      #- id: pyright
      #  name: Pyright type check
      #  entry: poetry run pyright
      #  language: system
      #  types: [file, python]
  - hooks:
      - args:
          - git-hook
          - pre-commit
        entry: dvc
        id: dvc-pre-commit
        language: system
        name: DVC pre-commit
        stages:
          - pre-commit
        verbose: true
        require_serial: true
      - args:
          - git-hook
          - pre-push
        entry: dvc
        id: dvc-pre-push
        language: system
        name: DVC pre-push
        stages:
          - pre-push
        require_serial: true
      - always_run: true
        args:
          - git-hook
          - post-checkout
        entry: dvc
        id: dvc-post-checkout
        language: system
        minimum_pre_commit_version: 2.2.0
        name: DVC post-checkout
        stages:
          - post-checkout
        require_serial: true
    repo: local
